module.exports = {
  PushSubscription: require('./PushSubscription'),
  Post: require('./Post'),
  Producto: require('./Producto'),
  Conversacion: require('./Conversacion'),
  Mensaje: require('./Mensaje'),
  Usuario: require('./Usuario'),
  Liga: require('./Liga'),
  Equipo: require('./Equipo'),
  Jugador: require('./Jugador'),
  Jornada: require('./Jornada'),
  Partido: require('./Partido'),
  Gol: require('./Gol'),
  Tarjeta: require('./Tarjeta'),
  Sancion: require('./Sancion'),
  WhatsappLog: require('./WhatsappLog'),
  LiguillaGrupo: require('./LiguillaGrupo'),
  LiguillaPartido: require('./LiguillaPartido'),
  Inscripcion: require('./Inscripcion'),
}
