const router = require('express').Router()
const auth = require('../middleware/auth')
const licencia = require('../middleware/licencia')
const roles = require('../middleware/roles')
const ctrl = require('../controllers/ligasController')
const inscCtrl = require('../controllers/inscripcionesController')

router.use(auth, licencia)
router.get('/', ctrl.getAll)
router.post('/', roles('admin_liga', 'superadmin'), ctrl.create)
router.get('/:id', ctrl.getOne)
router.put('/:id', roles('admin_liga', 'superadmin'), ctrl.update)
router.delete('/:id', roles('admin_liga', 'superadmin'), ctrl.remove)
router.post('/:id/clonar', roles('admin_liga', 'superadmin'), ctrl.clonar)
router.get('/:id/galeria', ctrl.galeriaGet)
router.post('/:id/galeria', roles('admin_liga', 'superadmin'), ctrl.galeriaAdd)
router.delete('/:id/galeria/:idx', roles('admin_liga', 'superadmin'), ctrl.galeriaDelete)
router.post('/:id/inscripciones/token', roles('admin_liga', 'superadmin'), inscCtrl.generarToken)
router.put('/:id/inscripciones/cerrar', roles('admin_liga', 'superadmin'), inscCtrl.cerrar)

module.exports = router
